#!/bin/bash

##### This script runs scDblFinder on a single input AnnData object #####


### Input arguments ###
# Define the sample barcode from cohort samples list.
ARRAYID="$1"
LINKER="../../metadata/snRNA_samples.txt"

# Sample ID
sample_name=$(sed "${ARRAYID}q;d" ${LINKER} | cut -f1)

# Cohort ID
cohort_name="Test"

# Input directory for results generated by Jupyter notebook analysis
input_dir=../../results/snRNA/individual_sample_annotated_raw_counts/

# Ouptut directory (will be created if not existing)
output_dir=../../results/snRNA/individual_sample_post-scDblFinder_raw_counts/
mkdir -p ${output_dir}
###


STARTTIME=`date`
echo $STARTTIME
echo "Analyzing $sample_name"
echo ""


# Run analysis Rscript
Rscript --verbose ../R/detect_AnnData_snRNA_doublets.R \
			-i ${input_dir} \
			-s ${sample_name} \
			-c ${cohort_name} \
			-o ${output_dir}


			
